# Generated by Django 5.1.4 on 2025-01-09 21:47

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="is_liked",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=content.models.profile_picture_file_path,
            ),
        ),
    ]
