# Generated by Django 5.1.4 on 2025-01-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="relations",
        ),
        migrations.AddField(
            model_name="like",
            name="is_unliked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="like",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="relation",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="content.profile",
            ),
        ),
    ]
